#!/bin/bash
# Build CSS bundle for members-portal
# 
# This script combines commonly-used CSS files into a single bundle.css
# for better performance (fewer HTTP requests).
#
# Run this after editing any of the bundled CSS files:
#   ./scripts/build-css-bundle.sh
#
# Files included in bundle:
#   - global.css (base styles, CSS variables)
#   - nav.css (navigation component)
#   - page.css (page layout)
#   - button.css (button styles)
#   - badge.css (badge/tag styles)
#   - modal.css (modal dialogs)
#   - toast.css (toast notifications)
#   - form.css (form elements)
#
# See GitHub issue #306 for pre-commit hook implementation

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
PORTAL_DIR="$PROJECT_ROOT/apps/members-portal"
STYLES_DIR="$PORTAL_DIR/styles"
BUNDLE_FILE="$STYLES_DIR/bundle.css"

# Bundled CSS files (order matters - base styles first)
CSS_FILES=(
    "$STYLES_DIR/global.css"
    "$STYLES_DIR/components/nav.css"
    "$STYLES_DIR/components/page.css"
    "$STYLES_DIR/components/button.css"
    "$STYLES_DIR/components/badge.css"
    "$STYLES_DIR/components/modal.css"
    "$STYLES_DIR/components/toast.css"
    "$STYLES_DIR/components/form.css"
    "$STYLES_DIR/components/profile-edit.css"
)

# Check all source files exist
for file in "${CSS_FILES[@]}"; do
    if [[ ! -f "$file" ]]; then
        echo "❌ Error: Missing CSS file: $file"
        exit 1
    fi
done

# Generate bundle with header
{
    echo "/**"
    echo " * CSS Bundle - Auto-generated"
    echo " * Generated: $(date '+%Y-%m-%d %H:%M:%S')"
    echo " * "
    echo " * DO NOT EDIT THIS FILE DIRECTLY!"
    echo " * Edit the source files and run: ./scripts/build-css-bundle.sh"
    echo " * "
    echo " * Included files:"
    for file in "${CSS_FILES[@]}"; do
        echo " *   - $(basename "$file")"
    done
    echo " */"
    echo ""
    
    # Concatenate all CSS files
    for file in "${CSS_FILES[@]}"; do
        echo "/* ========== $(basename "$file") ========== */"
        cat "$file"
        echo ""
        echo ""
    done
} > "$BUNDLE_FILE"

# Report
SIZE=$(wc -c < "$BUNDLE_FILE")
SIZE_KB=$((SIZE / 1024))
echo "✅ bundle.css updated (${SIZE_KB}KB / ${SIZE} bytes)"
echo "   Location: $BUNDLE_FILE"
