steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/ekklesia/members:latest'
      - '.'

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/ekklesia/members:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'members'
      - '--image=${_REGION}-docker.pkg.dev/$PROJECT_ID/ekklesia/members:latest'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=3000'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--min-instances=0'
      - '--max-instances=10'
      - '--set-env-vars=NODE_ENV=production,LOG_LEVEL=info,ZITADEL_ISSUER=https://auth.si-xj.org,ZITADEL_CLIENT_ID=340609127703243145,ZITADEL_REDIRECT_URI=https://members-ymzrguoifa-nw.a.run.app/callback'
      - '--set-secrets=SESSION_SECRET=members-session-secret:latest'

substitutions:
  _REGION: europe-west2

options:
  logging: CLOUD_LOGGING_ONLY
