# Ekklesia Portal - Production Configuration for GCP Cloud Run
database:
    # Cloud SQL connection using Unix socket
    uri: "postgresql+psycopg2://ekklesia_portal:${DB_PASSWORD}@/${DB_NAME}?host=/cloudsql/${CLOUD_SQL_CONNECTION}"
    fts_language: 'english'

app:
    instance_name: ekklesia_prod_portal
    insecure_development_mode: false
    force_ssl: true
    tos_url: /pages/tos
    imprint_url: /pages/imprint
    data_protection_url: /pages/data_protection
    enable_drafts: false
    faq_url: /pages/faq
    title: "Ekklesia Portal"
    fallback_language: "en"
    languages: ["en", "is"]
    timezone: "Atlantic/Reykjavik"
    login_visible: true
    internal_login_enabled: false
    source_code_url: "https://github.com/sosialistaflokkurinn/ekklesia"

browser_session:
    secret_key: "${SESSION_SECRET_KEY}"
    cookie_secure: true
    permanent_lifetime: 2592000  # 30 days

# Integration with Firebase Auth Members service
ekklesia_auth:
    display_name: "Kenni.is"
    client_id: "${FIREBASE_CLIENT_ID}"
    client_secret: "${FIREBASE_CLIENT_SECRET}"
    authorization_url: "https://ekklesia-prod-10-2025.web.app/auth"
    token_url: "https://europe-west2-ekklesia-prod-10-2025.cloudfunctions.net/handleKenniAuth"
    api_base_url: "https://ekklesia-prod-10-2025.web.app"
    required_role_for_login: null

share:
    use_url_shortener: false
    hashtag: "ekklesia"
    promote_account: "sosialistaflokkurinn"

# Disable exporters/importers in production (configure as needed)
importer: {}
exporter: {}
voting_modules: {}
