name: PII and Secrets Scan
on:
  pull_request:
    paths:
      - '**/*'
jobs:
  gitleaks-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        # NOTE: Gitleaks v2 requires a license key which is not configured.
        # Pre-commit hooks (git-hooks/pre-commit) and manual history purge provide
        # sufficient security. This automated scan is disabled in favor of:
        # 1. Pre-commit hook detection (blocks commits with secrets)
        # 2. Manual git-filter-repo purging (for historical cleanup)
        # 3. GitHub Actions security-hygiene.yml (automated issue tracking)
        # To re-enable, add GITLEAKS_LICENSE secret to GitHub org/repo settings
